// components/pingTuan/pingTuan.js
var that;
Component({
  /**
   * 组件的属性列表
   */
  properties: {
    flag:{
      type:Boolean//要接收的数据类型
    }
  },

  /**
   * 组件的初始数据
   */
  data: {
   banners:[
     "../../img/banner1.png",
     "../../img/banner1.png"
   ],
   //swiper配置
   indicatorDots:true,
   vertical:false,
   autoplay:true,
   circular:true,
   interval:5000,
   previousMargin:0,
   nextMargin:0,
   itemList:[
    "../../images/item1.png","../../images/item2.png","../../images/item3.png","../../images/item4.png","../../images/item5.png",
    "../../images/item6.png","../../images/item7.png","../../images/item8.png","../../images/item9.png","../../images/item10.png",
   ],
   fourItem:[
     {
       "title":'../../images/cp1.png',
       "image":'../../img/cpImg1.png'
     },
     {
      "title":'../../images/cp2.png',
      "image":'../../img/cpImg2.png'
    },
    {
      "title":'../../images/cp3.png',
      "image":'../../img/cpImg3.png'
    },{
      "title":'../../images/cp4.png',
      "image":'../../img/cpImg4.png'
    }
   ],
   scrollHeight: wx.getSystemInfoSync().windowHeight,
   // 是否显示回到顶部图标
   visual:false,
   topNum:0,
   imageList:[],
   newPd:[
     {
       "newImg":"../../img/new1.jpg",
       "newTxt":"[预售]细莫红糖姜茶",
       "newPrice":"72.0"
     },
     {
      "newImg":"../../img/new2.jpg",
      "newTxt":"[预售]细莫红糖姜茶",
      "newPrice":"72.0"
    },
    {
      "newImg":"../../img/new3.jpg",
      "newTxt":"[预售]细莫红糖姜茶",
      "newPrice":"72.0"
    },
    {
      "newImg":"../../img/new4.jpg",
      "newTxt":"[预售]细莫红糖姜茶",
      "newPrice":"72.0"
    },
    {
      "newImg":"../../img/new5.jpg",
      "newTxt":"[预售]细莫红糖姜茶",
      "newPrice":"72.0"
    },
    {
      "newImg":"../../img/new6.jpg",
      "newTxt":"[预售]细莫红糖姜茶",
      "newPrice":"72.0"
    }
   ],
   pdList:[
     {
       "brandImg":"../../img/brand1.png",
       "brandName":"TUSCAN’S",
       "brandTxt":"时代集团包包专场",
       "brandPd":[
         {
           "bpImg":"../../img/bp1.jpg",
           "bpInfo":"珑骧同款旅行…",
           "bpPrice":"308.0"
         },
         {
          "bpImg":"../../img/bp2.jpg",
          "bpInfo":"BALLY同皮手…",
          "bpPrice":"468.0"
         },
         {
          "bpImg":"../../img/bp3.png",
          "bpInfo":"LV同款T字水…",
          "bpPrice":"318.0"
         },
       ]
     },
     {
      "brandImg":"../../img/brand2.png",
      "brandName":"细莫果园",
      "brandTxt":"基地现采现发专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp21.jpg",
          "bpInfo":"黄土高原冰糖…",
          "bpPrice":"139.0"
        },
        {
          "bpImg":"../../img/bp22.jpg",
          "bpInfo":"麻阳绵密冰糖…",
          "bpPrice":"36.0"
        },
        {
          "bpImg":"../../img/bp23.jpg",
          "bpInfo":"露天冬草莓60…",
          "bpPrice":"49.9"
        }
      ]
    },
    {
      "brandImg":"../../img/brand3.png",
      "brandName":"TUSCAN’S",
      "brandTxt":"时代集团包包专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp31.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        },
        {
          "bpImg":"../../img/bp32.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        },
        {
          "bpImg":"../../img/bp33.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand3.png",
      "brandName":"TUSCAN’S",
      "brandTxt":"时代集团包包专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp31.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        },
        {
          "bpImg":"../../img/bp32.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        },
        {
          "bpImg":"../../img/bp33.jpg",
          "bpInfo":"珑骧同款旅行…",
          "bpPrice":"308.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand3.png",
      "brandName":"细莫海鲜",
      "brandTxt":"寰宇全球海鲜专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp31.jpg",
          "bpInfo":"舟山野生海钓…",
          "bpPrice":"135.0"
        },
        {
          "bpImg":"../../img/bp32.jpg",
          "bpInfo":"青岛海捕大虾…",
          "bpPrice":"118.9"
        },
        {
          "bpImg":"../../img/bp33.jpg",
          "bpInfo":"舟山野生海捕…",
          "bpPrice":"87.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand4.png",
      "brandName":"细莫坚果",
      "brandTxt":"超级工厂专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp41.jpg",
          "bpInfo":"细莫开心过…",
          "bpPrice":"95.0"
        },
        {
          "bpImg":"../../img/bp42.jpg",
          "bpInfo":"细莫纸皮腰果…",
          "bpPrice":"85.0"
        },
        {
          "bpImg":"../../img/bp43.jpg",
          "bpInfo":"细莫巴旦木…",
          "bpPrice":"52.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand5.png",
      "brandName":"陈克明食品",
      "brandTxt":"面、米、粮、油专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp51.jpg",
          "bpInfo":"陈克明七成苦…",
          "bpPrice":"99.0"
        },
        {
          "bpImg":"../../img/bp52.jpg",
          "bpInfo":"陈克明儿童面…",
          "bpPrice":"24.8"
        },
        {
          "bpImg":"../../img/bp53.jpg",
          "bpInfo":"陈克明小包装…",
          "bpPrice":"11.9"
        }
      ]
    },
    {
      "brandImg":"../../img/brand6.png",
      "brandName":"光明乳业",
      "brandTxt":"有机好牛奶专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp61.jpg",
          "bpInfo":"光明天然有机奶…",
          "bpPrice":"58.7"
        },
        {
          "bpImg":"../../img/bp62.jpg",
          "bpInfo":"光明脱脂纯牛奶…",
          "bpPrice":"84.7"
        },
        {
          "bpImg":"../../img/bp63.jpg",
          "bpInfo":"光明学生奶粉…",
          "bpPrice":"104.2"
        }
      ]
    },
    {
      "brandImg":"../../img/brand7.png",
      "brandName":"斯维诗",
      "brandTxt":"进口自然营养品专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp71.jpg",
          "bpInfo":"Swisse深海鱼油…",
          "bpPrice":"86.0"
        },
        {
          "bpImg":"../../img/bp72.jpg",
          "bpInfo":"Swisse奶蓟草…",
          "bpPrice":"65.0"
        },
        {
          "bpImg":"../../img/bp73.jpg",
          "bpInfo":"Swisse高钙含…",
          "bpPrice":"102.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand8.png",
      "brandName":"贵人鸟",
      "brandTxt":"冬季童鞋专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp81.jpg",
          "bpInfo":"贵人鸟男童运动鞋…",
          "bpPrice":"86.0"
        },
        {
          "bpImg":"../../img/bp82.jpg",
          "bpInfo":"贵人鸟女童运动鞋…",
          "bpPrice":"65.0"
        },
        {
          "bpImg":"../../img/bp83.jpg",
          "bpInfo":"贵人鸟男童运动鞋…",
          "bpPrice":"102.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand9.png",
      "brandName":"黛安芬",
      "brandTxt":"全球知名内衣专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp91.jpg",
          "bpInfo":"黛安芬水盈玫…",
          "bpPrice":"495.0"
        },
        {
          "bpImg":"../../img/bp92.jpg",
          "bpInfo":"黛安芬咖啡炭…",
          "bpPrice":"448.0"
        },
        {
          "bpImg":"../../img/bp93.jpg",
          "bpInfo":"黛安芬恒温棉…",
          "bpPrice":"449.0"
        }
      ]
    },
    {
      "brandImg":"../../img/brand10.png",
      "brandName":"UGG",
      "brandTxt":"轻奢羊毛皮靴专场",
      "brandPd":[
        {
          "bpImg":"../../img/bp101.jpg",
          "bpInfo":"UGG2021秋冬…",
          "bpPrice":"86.0"
        },
        {
          "bpImg":"../../img/bp102.jpg",
          "bpInfo":"UGG2021秋冬…",
          "bpPrice":"65.0"
        },
        {
          "bpImg":"../../img/bp103.jpg",
          "bpInfo":"UGG2021秋冬…",
          "bpPrice":"102.0"
        }
      ]
    },
   ],
   jpList:[
    {
      "productImg":"../../img/jp1.jpg",
      "productTitle":"健达Kindrmix灯笼虎年音乐糖果年货礼盒",
      "productPrice":"98",
      "productSale":"3499",
      "productPrecent":"70%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp2.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp3.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp4.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp5.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp6.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp7.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家",
    },
    {
      "productImg":"../../img/jp8.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp9.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp10.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp11.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp12.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp13.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp14.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp15.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp16.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp17.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp18.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp19.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp20.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp21.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp22.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp23.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp24.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp25.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp26.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp27.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp28.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp29.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp30.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp31.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp32.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp33.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp34.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp35.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
    {
      "productImg":"../../img/jp36.jpg",
      "productTitle":"【虎年限定】不莱玫迪士尼米奇腋下包",
      "productPrice":"219.0",
      "productSale":"219",
      "productPrecent":"20%",
      "productTxt":"心意好礼 年味到家"
    },
   ],
    imageList:[]
  },
  methods: {
    //实时监听滚动条位置,显示/不显示回到顶部图片
    onPageScroll:function(e) {
      let scrollTop = e.detail.scrollTop;
      console.log(scrollTop);
      if (scrollTop < this.data.scrollHeight) {
        this.setData({
          visual: false
        })
      } else {
        this.setData({
          visual: true
        })
      }
    },
    //点击回到顶部图片方法
    scrollToTop() {
      this.setData({
        topNum: 0,
        visual: false
      })
    },
    itemTo(){

    },
    imageLoad: function(e) {
        let that=this;
        var $width=e.detail.width,    //获取图片真实宽度
            $height=e.detail.height,
            ratio=$width/$height;    //图片的真实宽高比例
        var viewWidth=340,           //设置图片显示宽度，左右留有16rpx边距
            viewHeight=340/ratio;    //计算的高度值
        var image=that.data.jpList; 
        //将图片的datadata-index作为image对象的key,然后存储图片的宽高值
        image[e.target.dataset.index]={
            width:viewWidth,
            height:viewHeight
        }
        that.setData({
          imageList:image
        })
    }
  },
  lifetimes:{
    ready(){
        
    }
  }
})
